### ISSUE TITLE
TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by markddavidoff** [serverless/serverless-local-schedule#10]
Stack Trace:
```
TypeError: Cannot read property 'match' of undefined
    at ServerlessLocalCrontabs.convertCrontabs (/Users/markddavidoff/PycharmProjects/apheleia/pull_request_reminder/node_modules/serverless-local-schedule/index.js:73:37)
    at BbPromise.reduce (/Users/markddavidoff/.nvm/versions/node/v9.2.0/lib/node_modules/serverless/lib/classes/PluginManager.js:408:55)
From previous event:
    at PluginManager.invoke (/Users/markddavidoff/.nvm/versions/node/v9.2.0/lib/node_modules/serverless/lib/classes/PluginManager.js:408:22)
    at PluginManager.spawn (/Users/markddavidoff/.nvm/versions/node/v9.2.0/lib/node_modules/serverless/lib/classes/PluginManager.js:426:17)
    at Deploy.BbPromise.bind.then (/Users/markddavidoff/.nvm/versions/node/v9.2.0/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:117:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (/Users/markddavidoff/.nvm/versions/node/v9.2.0/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:107:10)
    at BbPromise.reduce (/Users/markddavidoff/.nvm/versions/node/v9.2.0/lib/node_modules/serverless/lib/classes/PluginManager.js:408:55)
From previous event:
    at PluginManager.invoke (/Users/markddavidoff/.nvm/versions/node/v9.2.0/lib/node_modules/serverless/lib/classes/PluginManager.js:408:22)
    at PluginManager.run (/Users/markddavidoff/.nvm/versions/node/v9.2.0/lib/node_modules/serverless/lib/classes/PluginManager.js:439:17)
    at variables.populateService.then (/Users/markddavidoff/.nvm/versions/node/v9.2.0/lib/node_modules/serverless/lib/Serverless.js:106:33)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Serverless.run (/Users/markddavidoff/.nvm/versions/node/v9.2.0/lib/node_modules/serverless/lib/Serverless.js:93:6)
    at serverless.init.then (/Users/markddavidoff/.nvm/versions/node/v9.2.0/lib/node_modules/serverless/bin/serverless:43:28)
    at /Users/markddavidoff/.nvm/versions/node/v9.2.0/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
    at /Users/markddavidoff/.nvm/versions/node/v9.2.0/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:149:15)
From previous event:
    at initializeErrorReporter.then (/Users/markddavidoff/.nvm/versions/node/v9.2.0/lib/node_modules/serverless/bin/serverless:43:6)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at __dirname (/Users/markddavidoff/.nvm/versions/node/v9.2.0/lib/node_modules/serverless/bin/serverless:28:46)
    at Object.<anonymous> (/Users/markddavidoff/.nvm/versions/node/v9.2.0/lib/node_modules/serverless/bin/serverless:67:4)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3

```

Relevant bits of `serverless.yml`:
```
functions:
  chef:
    handler: chef.lambda_handler
    events:
      - schedule:
          # 9:45 am PST
          cron: cron(45 9 ? * MON-FRI *)
          timezone: America/Los_Angeles
          enabled: true
      - schedule:
          # 1 pm PST
          cron: cron(45 13 ? * MON-FRI *)
          timezone: America/Los_Angeles
          enabled: true
      - schedule:
          # 4:00 pm PST
          cron: cron(0 16 ? * MON-FRI *)
          timezone: America/Los_Angeles
          enabled: true
  b2c:
    handler: b2c.lambda_handler
    events:
      - schedule:
          # 9:45 am PST
          cron: cron(45 9 ? * MON-FRI *)
          timezone: America/Los_Angeles
          enabled: true
      - schedule:
          # 1 pm PST
          cron: cron(45 13 ? * MON-FRI *)
          timezone: America/Los_Angeles
          enabled: true
      - schedule:
          # 4:00 pm PST
          cron: cron(0 16 ? * MON-FRI *)
          timezone: America/Los_Angeles
          enabled: true
  consumer:
    handler: consumer.lambda_handler
    events:
      - schedule:
          # 9:45 am PST
          cron: cron(45 9 ? * MON-FRI *)
          enabled: true
      - schedule:
          # 1 pm PST
          cron: cron(45 13 ? * MON-FRI *)
          timezone: America/Los_Angeles
          enabled: true
      - schedule:
          # 4:00 pm PST
          cron: cron(0 16 ? * MON-FRI *)
          timezone: America/Los_Angeles
          enabled: true
  themis_daily:
    handler: themis.daily_reminders_lambda_handler
    events:
      - schedule:
          # 9:45 am PST
          cron: cron(45 9 ? * MON-FRI *)
          timezone: America/Los_Angeles
          enabled: true
  themis_chef_weekly:
    handler: themis.weekly_chef_reminder_lambda_handler
    events:
      - schedule:
          # 9:45 am PST on mondays
          cron: cron(45 9 ? * MON *)
          enabled: true
          environment:
            SLACK_CHANNEL: eng-chefteam
  themis_b2c_weekly:
    handler: themis.weekly_b2c_reminder_lambda_handler
    events:
      - schedule:
          # 9:45 am PST on mondays
          cron: cron(45 9 ? * MON *)
          timezone: America/Los_Angeles
          enabled: true
          environment:
            SLACK_CHANNEL: eng-clubcomputer
  themis_consumer_weekly:
    handler: themis.weekly_consumer_reminder_lambda_handler
    events:
      - schedule:
          # 9:45 am PST on mondays
          cron: cron(45 9 ? * MON *)
          timezone: America/Los_Angeles
          enabled: true
          environment:
            SLACK_CHANNEL: eng-consumer
```
