### ISSUE TITLE
Add support for stepFunctions

### ISSUE THREAD

**Issue by pal** [serverless/serverless-local-schedule#13]
Would be awesome if this plugin could be used for all places where we can add cron-like schedules, particularly if support of scheduling step functions. 

I'm using this plugin to configure AWS Step Functions in Serverless:  https://github.com/horike37/serverless-step-functions

```
stepFunctions:
  stateMachines:
    myStateMachine:
      events:
        - schedule:
          rate: cron(0 6 * * ? *)
          timezone: Europe/Stockholm
```
