### ISSUE TITLE
TypeError: schedule.rate.match is not a function

### ISSUE THREAD

**Issue by gabrielecuccu** [serverless/serverless-local-schedule#20]
Hi, this error started today on my nightly deploy task:

```
Serverless: Converting local crontabs to UTC crontabs...
 
 Type Error ----------------------------------------------
 
  TypeError: schedule.rate.match is not a function
      at ServerlessLocalCrontabs.convertCrontabs (/root/project/build/node_modules/serverless-local-schedule/index.js:73:37)
      at PluginManager.invoke (/root/project/build/node_modules/serverless/lib/classes/PluginManager.js:580:20)
      at async PluginManager.spawn (/root/project/build/node_modules/serverless/lib/classes/PluginManager.js:602:5)
      at async Object.before:deploy:deploy [as hook] (/root/project/build/node_modules/serverless/lib/plugins/deploy.js:61:11)
      at async PluginManager.invoke (/root/project/build/node_modules/serverless/lib/classes/PluginManager.js:580:9)
      at async PluginManager.run (/root/project/build/node_modules/serverless/lib/classes/PluginManager.js:640:7)
      at async Serverless.run (/root/project/build/node_modules/serverless/lib/Serverless.js:457:5)
      at async /root/project/build/node_modules/serverless/scripts/serverless.js:803:9
```

I believe it relates to this bit of configuration in serverless.yml:

```
  subscriptions-f:
    environment: ${file(.env.json)}
    handler: dist/subscriptions-f-handler.handler
    timeout: 900
    events:
      - sns:
          arn: ${file(.env.json):USER_CHAIN_TOPIC}
      - schedule:
          rate: cron(0 * * * ? *)
          timezone: Europe/London
          input:
            topic: 'main'
```

I was able to deploy the same code to UAT and to Production 2 days ago - this issue started on nightly provisioning only.

I don't know if it matters, I have been using serverless-local-schedule for about 1 year but with frameworkVersion < 2.
Now I'm using frameworkVersion: "2"

Any idea? Thank you!
