### ISSUE TITLE
Run every X minutes option

### ISSUE THREAD

**Issue by mrpehlivan** [serverless/serverless-local-schedule#23]
Hi Guys,

First of all, thank you for the plugin to run the cron job on different timezones. I am wondering is this plugin support run every x minute option? 

For example : 

I want to run my cron every 15 minutes between 1 am and 2 am in Europe/Berlin timezone.
```
events:
    - schedule:
        rate: cron(0/15 1,2 * * ? *)
        timezone: Europe/Berlin
````
