### ISSUE TITLE
Converts only the first schedule with timezone for function with multiple schedules

### ISSUE THREAD

**Issue by gazal-k** [serverless/serverless-local-schedule#6]
For a function with multiple schedules each with timezone parameter

```yml
events:
  - schedule:
      description: FULL
      rate: cron(0 4 * * ? *)
      timezone: Australia/Melbourne
  - schedule:
      description: PARTIAL
      rate: cron(0/15 0-3 * * ? *)
      timezone: Australia/Melbourne
```
only the first one is converted correctly
