### ISSUE TITLE
Breaks support for `schedule.name` property

### ISSUE THREAD

**Issue by andrhamm** [serverless/serverless-local-schedule#8]
I'm using the schedule `name` property to make it easier to grok my schedules in the AWS Console. The first deploy worked as expected but subsequent deploys failed with the following error. When I commented out the `name` property, deploys started working as expected (although the names are auto-generated. The plugin should use the `name` property plus some unique suffix.

```
An error occurred: ScaleUnderscoredynamodbUnderscorecapacityEventsRuleSchedule3 - dynamodb-scaling already exists in stack [stack arn]
```

```
- schedule:
          rate: cron(0 0-8,12-23 * * ? *)
          timezone: America/New_York
          name: dynamodb-scaling
          description: Lambda trigger to scale DynamoDB table
```
